feat: upgrate to latest nitro version

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -8,9 +8,9 @@ inputs:
   root-directory:
     description: The directory within your project, in which your code is located. Leave this field empty if your code is not located in a subdirectory"
     default: "./"
-  ios-scheme:
+  scheme:
     description: "The name of the iOS scheme"
-  ios-xcconfig-path:
+  xcconfig-path:
     description: "Path to a custom xcconfig file. The path relative to project root directory where the custom `.xcconfig` file is located"
 
   # App Versioning
@@ -24,30 +24,30 @@ inputs:
     description: "Disable automatic version code generation. By default will generate a timestamp based number and set the version code. Available Options: (`yes` / `no`)"
 
   # App Signing
-  ios-certificate-url:
+  certificate-url:
     description: "Certificate url. The url to download and install the certificate"
-  ios-certificate-base64:
+  certificate-base64:
     description: "Certificate base64. The certificate base64 string enconded."
-  ios-certificate-passphrase:
+  certificate-passphrase:
     description: "Certificate passphrase"
-  ios-codesigning-identity:
+  codesigning-identity:
     description: "Codesigning identity"
-  ios-provisioning-profile-urls:
+  provisioning-profile-urls:
     description: "Provisioning profile urls. A string containing a '|' separated values where provisioning profiles are located (e.g. `url1|url2``)"
-  ios-provisioning-profiles-base64:
+  provisioning-profiles-base64:
     description: "Provisioning profiles in base64 format. A string containing a '|' separated values with provisioning profiles base64 encoded (e.g. `bXktcHJvdmlzaW9uaW5nLXByb2ZpbGUtY29udGVudC0x|bXktcHJvdmlzaW9uaW5nLXByb2ZpbGUtY29udGVudC0y`)"
-  ios-provisioning-profile-specifier:
+  provisioning-profile-specifier:
     description: "Provisioning profile specifier. The name of the provisioning profile when using a single one"
-  ios-team-id:
+  team-id:
     description: "Team ID. Specify the Team ID you want to use for the Apple Developer Portal"
-  ios-export-method:
+  export-method:
     description: "Export Method. The export method used to generate the IPA. Available Options: (`ad-hoc` / `app-store`)"
     default: "ad-hoc"
 
   # Caching
   cache-provider:
     description: "Cache provider where cache artifacts will be persisted. Available Options: (`fs`: File system / `github`: Uses Github cache action / `s3`: Amazon - Simple Storage Service)"
-    default: "github"
+    default: "s3"
   disable-cache:
     description: "When setting this option to `yes` build cache optimizations won't be performed.  Available Options: (`yes` / `no`)"
   cache-env-var-lookup-keys:
@@ -121,19 +121,6 @@ runs:
       shell: bash
       run: |
         env HOMEBREW_NO_AUTO_UPDATE=1 brew install fastlane pigz
-    - name: Configure Nitro Cache
-      uses: actions/cache@v2
-      if: ${{ inputs.cache-provider == 'github' }}
-      with:
-        path: |
-          ~/.nitro/cache/*
-        key: nitro-cache-${{ hashFiles('~/.nitro/cache/*') }}
-        restore-keys: nitro-cache-
-    - name: Install Envman
-      run: |
-        curl -fL https://github.com/bitrise-io/envman/releases/download/2.3.3/envman-"$(uname -s)"-"$(uname -m)" > /usr/local/bin/envman
-        chmod +x /usr/local/bin/envman
-      shell: bash
     - name: Run Nitro cli
       id: nitro-cli
       shell: bash
@@ -179,12 +166,12 @@ runs:
           args+=("--root-directory" "${{ inputs.root-directory }}")
         fi
 
-        if [[ -n "${{ inputs.ios-scheme }}" ]]; then
-          args+=("--ios-scheme" "${{ inputs.ios-scheme }}")
+        if [[ -n "${{ inputs.scheme }}" ]]; then
+          args+=("--scheme" "${{ inputs.scheme }}")
         fi
 
-        if [[ -n "${{ inputs.ios-xcconfig-path }}" ]]; then
-          args+=("--ios-xcconfig-path" "${{ inputs.ios-xcconfig-path }}")
+        if [[ -n "${{ inputs.xcconfig-path }}" ]]; then
+          args+=("--xcconfig-path" "${{ inputs.xcconfig-path }}")
         fi
 
         # --------------
@@ -213,45 +200,45 @@ runs:
         # App Signing
         # -----------
 
-        if [[ -n "${{ inputs.ios-certificate-base64 }}" && -n "${{ inputs.ios-certificate-url }}" ]]; then
-          echo "⚠️ You cannot provide both: 'ios-certificate-base64' and 'ios-certificate-url'"
+        if [[ -n "${{ inputs.certificate-base64 }}" && -n "${{ inputs.certificate-url }}" ]]; then
+          echo "⚠️ You cannot provide both: 'certificate-base64' and 'certificate-url'"
           exit 1
         fi
 
-        if [[ -z "${{ inputs.ios-certificate-base64 }}" && -z "${{ inputs.ios-certificate-url }}" ]]; then
-          echo "⚠️ You must provide at least one of these arguments: 'ios-certificate-base64', 'ios-certificate-url'"
+        if [[ -z "${{ inputs.certificate-base64 }}" && -z "${{ inputs.certificate-url }}" ]]; then
+          echo "⚠️ You must provide at least one of these arguments: 'certificate-base64', 'certificate-url'"
           exit 1
         fi
 
-        if [[ -n "${{ inputs.ios-certificate-base64 }}" ]]; then
-          echo -n "${{ inputs.ios-certificate-base64 }}" | base64 --decode --output "${RUNNER_TEMP}/certificate.p12"
-          args+=("--ios-certificate-url" "file://${RUNNER_TEMP}/certificate.p12")
+        if [[ -n "${{ inputs.certificate-base64 }}" ]]; then
+          echo -n "${{ inputs.certificate-base64 }}" | base64 --decode --output "${RUNNER_TEMP}/certificate.p12"
+          args+=("--certificate-url" "file://${RUNNER_TEMP}/certificate.p12")
         else
-          args+=("--ios-certificate-url" "${{ inputs.ios-certificate-url }}")
+          args+=("--certificate-url" "${{ inputs.certificate-url }}")
         fi
 
-        if [[ -n "${{ inputs.ios-certificate-passphrase }}" ]]; then
-          args+=("--ios-certificate-passphrase" "${{ inputs.ios-certificate-passphrase }}")
+        if [[ -n "${{ inputs.certificate-passphrase }}" ]]; then
+          args+=("--certificate-passphrase" "${{ inputs.certificate-passphrase }}")
         fi
 
-        if [[ -n "${{ inputs.ios-codesigning-identity }}" ]]; then
-          args+=("--ios-codesigning-identity" "${{ inputs.ios-codesigning-identity }}")
+        if [[ -n "${{ inputs.codesigning-identity }}" ]]; then
+          args+=("--codesigning-identity" "${{ inputs.codesigning-identity }}")
         fi
 
-        if [[ -n "${{ inputs.ios-provisioning-profile-urls }}" && -n "${{ inputs.ios-provisioning-profiles-base64 }}" ]]; then
-          echo "⚠️ You cannot provide both 'ios-provisioning-profile-urls' and 'ios-provisioning-profiles-base64'"
+        if [[ -n "${{ inputs.provisioning-profile-urls }}" && -n "${{ inputs.provisioning-profiles-base64 }}" ]]; then
+          echo "⚠️ You cannot provide both 'provisioning-profile-urls' and 'provisioning-profiles-base64'"
           exit 1
         fi
 
-        if [[ -z "${{ inputs.ios-provisioning-profile-urls }}" && -z "${{ inputs.ios-provisioning-profiles-base64 }}" ]]; then
-          echo "⚠️ You must provide at least one of these arguments: 'ios-provisioning-profile-urls', 'ios-provisioning-profiles-base64'"
+        if [[ -z "${{ inputs.provisioning-profile-urls }}" && -z "${{ inputs.provisioning-profiles-base64 }}" ]]; then
+          echo "⚠️ You must provide at least one of these arguments: 'provisioning-profile-urls', 'provisioning-profiles-base64'"
           exit 1
         fi
 
-        if [[ -n "${{ inputs.ios-provisioning-profile-urls }}" ]]; then
-          IFS='|' ios_provisioning_profile_urls_array=("${{ inputs.ios-provisioning-profile-urls }}")
+        if [[ -n "${{ inputs.provisioning-profile-urls }}" ]]; then
+          IFS='|' ios_provisioning_profile_urls_array=("${{ inputs.provisioning-profile-urls }}")
         else
-          IFS='|' ios_provisioning_profiles_base64_array=("${{ inputs.ios-provisioning-profiles-base64 }}")
+          IFS='|' ios_provisioning_profiles_base64_array=("${{ inputs.provisioning-profiles-base64 }}")
 
           for i in "${!ios_provisioning_profiles_base64_array[@]}"
           do
@@ -262,18 +249,18 @@ runs:
         fi
 
         # shellcheck disable=SC2206
-        args+=("--ios-provisioning-profile-urls" ${ios_provisioning_profile_urls_array[@]})
+        args+=("--provisioning-profile-urls" ${ios_provisioning_profile_urls_array[@]})
 
-        if [[ -n "${{ inputs.ios-provisioning-profile-specifier }}" ]]; then
-          args+=("--ios-provisioning-profile-specifier" "${{ inputs.ios-provisioning-profile-specifier }}")
+        if [[ -n "${{ inputs.provisioning-profile-specifier }}" ]]; then
+          args+=("--provisioning-profile-specifier" "${{ inputs.provisioning-profile-specifier }}")
         fi
 
-        if [[ -n "${{ inputs.ios-team-id }}" ]]; then
-          args+=("--ios-team-id" "${{ inputs.ios-team-id }}")
+        if [[ -n "${{ inputs.team-id }}" ]]; then
+          args+=("--team-id" "${{ inputs.team-id }}")
         fi
 
-        if [[ -n "${{ inputs.ios-export-method }}" ]]; then
-          args+=("--ios-export-method" "${{ inputs.ios-export-method }}")
+        if [[ -n "${{ inputs.export-method }}" ]]; then
+          args+=("--export-method" "${{ inputs.export-method }}")
         fi
 
         # -------
@@ -281,11 +268,7 @@ runs:
         # -------
 
         if [[ -n "${{ inputs.cache-provider }}" ]]; then
-          if [[ "${{ inputs.cache-provider }}" == "github" ]]; then
-            args+=("--cache-provider" "fs")
-          else
-            args+=("--cache-provider" "${{ inputs.cache-provider }}")
-          fi
+          args+=("--cache-provider" "${{ inputs.cache-provider }}")
         fi
 
         # shellcheck disable=SC2154
@@ -338,8 +321,12 @@ runs:
         # Nitro Cli execution
         # -------------------
 
-        BITRISE_STEP_VERSION=1.1.1
-        BIN_FILE="nitro-macos"
+        BITRISE_STEP_VERSION=4.0.0
+
+        MACOS_BIN_FILE="nitro-macos"
+        LINUX_BIN_FILE="nitro-linux"
+
+        BIN_FILE=$([[ "$(uname)" == "Darwin" ]] && echo "${MACOS_BIN_FILE}" || echo "${LINUX_BIN_FILE}")
         BIN_FILE_PATH="${RUNNER_TEMP}/nitro"
 
         # Download cli release
